//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jcRSS.DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feeds2Content
    {
        public Feeds2Content()
        {
            this.Users2Feeds2Content = new HashSet<Users2Feeds2Content>();
        }
    
        public int RowStatusID { get; set; }
        public int ContentID { get; set; }
        public int FeedID { get; set; }
        public int ID { get; set; }
        public System.DateTime Modified { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual Content Content { get; set; }
        public virtual Feed Feed { get; set; }
        public virtual RowStatus RowStatus { get; set; }
        public virtual ICollection<Users2Feeds2Content> Users2Feeds2Content { get; set; }
    }
}
