//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jcRSS.DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feed
    {
        public Feed()
        {
            this.Feeds2Content = new HashSet<Feeds2Content>();
        }
    
        public int RowStatusID { get; set; }
        public string URL { get; set; }
        public string Title { get; set; }
        public System.DateTime Modified { get; set; }
        public System.DateTime Created { get; set; }
        public int ID { get; set; }
    
        public virtual RowStatus RowStatus { get; set; }
        public virtual ICollection<Feeds2Content> Feeds2Content { get; set; }
    }
}
