//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jcRSS.DataLayer.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class jcRSSEntities : DbContext
    {
        public jcRSSEntities()
            : base("name=jcRSSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Content> Contents { get; set; }
        public virtual DbSet<Feed> Feeds { get; set; }
        public virtual DbSet<Feeds2Content> Feeds2Content { get; set; }
        public virtual DbSet<RowStatus> RowStatuses { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Users2Feeds2Content> Users2Feeds2Content { get; set; }
    }
}
