//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jcRSS.DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RowStatus
    {
        public RowStatus()
        {
            this.Contents = new HashSet<Content>();
            this.Feeds = new HashSet<Feed>();
            this.Feeds2Content = new HashSet<Feeds2Content>();
            this.Users = new HashSet<User>();
            this.Users2Feeds2Content = new HashSet<Users2Feeds2Content>();
        }
    
        public int ID { get; set; }
        public System.DateTime Modified { get; set; }
        public System.DateTime Created { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Content> Contents { get; set; }
        public virtual ICollection<Feed> Feeds { get; set; }
        public virtual ICollection<Feeds2Content> Feeds2Content { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<Users2Feeds2Content> Users2Feeds2Content { get; set; }
    }
}
