//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jcRSS.DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Users2Feeds2Content = new HashSet<Users2Feeds2Content>();
        }
    
        public int RowStatusID { get; set; }
        public string Username { get; set; }
        public System.Guid Password { get; set; }
        public bool IsConfirmed { get; set; }
        public string EmailAddress { get; set; }
        public System.DateTime Modified { get; set; }
        public System.DateTime Created { get; set; }
        public int ID { get; set; }
    
        public virtual RowStatus RowStatus { get; set; }
        public virtual ICollection<Users2Feeds2Content> Users2Feeds2Content { get; set; }
    }
}
