//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jcRSS.DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users2Feeds2Content
    {
        public int ID { get; set; }
        public System.DateTime Modified { get; set; }
        public System.DateTime Created { get; set; }
        public int RowStatusID { get; set; }
        public int Feeds2ContentID { get; set; }
        public int HasRead { get; set; }
        public int UserID { get; set; }
    
        public virtual Feeds2Content Feeds2Content { get; set; }
        public virtual RowStatus RowStatus { get; set; }
        public virtual User User { get; set; }
    }
}
